project:
  type: book
execute:
  freeze: auto

book:
  title: "Rパッケージ活用事例集"
  author: "データサイエンス関連基礎調査部会"
  chapters:
    - index.qmd
    - articles/*.qmd

format:
  html:
    number-sections: false
    theme: flatly
    html-math-method: katex

editor: visual

