project:
  type: website

execute:
  freeze: auto
  error: true

website:
  title: "Rパッケージ活用事例集"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - auto: "articles/*.qmd"

format:
  html:
    number-sections: false
    theme: flatly
    html-math-method: katex

editor: visual
