project:
  type: book
  output-dir: docs

book:
  title: "dswg-book"
  author: "Norah Jones"
  date: "2024/10/16"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - actuar.qmd
    - aglm.qmd
    - ALEPlot.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

