project:
  type: book
execute:
  freeze: auto

book:
  title: "Rパッケージ活用事例集"
  author: "データサイエンス関連基礎調査WG"
  chapters:
    - index.qmd
    - articles/actuar.qmd
    - articles/aglm.qmd
    - articles/ALEPlot.qmd
    - articles/C50.qmd
    - articles/class.Rmd
    - articles/corrplot.qmd
    - articles/crosstable.qmd
    - articles/DALEX.qmd
    - articles/distr.qmd
    - articles/distrEx.qmd
    - articles/dplyr.qmd
    - articles/e1071.qmd
    - articles/evd.qmd
    - articles/forcats.qmd
    - articles/gghighlight.qmd
    - articles/igraph.qmd
    - articles/iml.qmd
    - articles/lifecontingencies.qmd
    - articles/makedummies.qmd
    - articles/mlbench.qmd
    - articles/palmerpenguins.qmd
    - articles/partykit.Rmd
    - articles/pdp.qmd
    - articles/pROC.qmd
    - articles/psych.qmd
    - articles/purrr.qmd
    - articles/randomForest.Rmd
    - articles/ranger.Rmd
#    - articles/recipes.qmd
    - articles/rpart.qmd
    - articles/rsample.qmd
    - articles/shapviz.qmd
    - articles/skimr.qmd
    - articles/survival.qmd
    - articles/tuneRanger.Rmd
#    - articles/YieldCurve.qmd
#    - articles/quantmod.qmd
#    - articles/datatable.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    html-math-method: katex

editor: visual

