project:
  type: book
execute:
  freeze: auto

book:
  title: "Rパッケージ活用事例集"
  author: "データサイエンス関連基礎調査WG"
  chapters:
    - index.qmd
    - qmds/actuar.qmd
    - qmds/aglm.qmd
    - qmds/ALEPlot.qmd
    - qmds/C50.qmd
    - qmds/class.Rmd
    - qmds/corrplot.qmd
    - qmds/crosstable.qmd
    - qmds/DALEX.qmd
    - qmds/distr.qmd
    - qmds/distrEx.qmd
    - qmds/dplyr.qmd
    - qmds/e1071.qmd
    - qmds/forcats.qmd
    - qmds/gghighlight.qmd
    - qmds/igraph.qmd
    - qmds/iml.qmd
    - qmds/lifecontingencies.qmd
    - qmds/makedummies.qmd
    - qmds/mlbench.qmd
    - qmds/palmerpenguins.qmd
    - qmds/partykit.Rmd
    - qmds/pdp.qmd
    - qmds/pROC.qmd
    - qmds/psych.qmd
    - qmds/purrr.qmd
    - qmds/randomForest.Rmd
    - qmds/ranger.Rmd
#    - qmds/recipes.qmd
    - qmds/rsample.qmd
    - qmds/shapviz.qmd
    - qmds/skimr.qmd
    - qmds/survival.qmd
    - qmds/tuneRanger.Rmd
#    - qmds/YieldCurve.qmd
#    - qmds/quantmod.qmd
#    - qmds/datatable.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    html-math-method: katex

editor: visual

