---
title: "gghighlight"
author: "データサイエンス関連基礎調査WG"
date: "`r Sys.Date()`"
format:
  html:
    fig-width: 6
    fig-height: 3
---

```{r setup, include=FALSE}

# install packages
pkgs <- c("ggplot2", "gghighlight", "tibble")
for (pkg in pkgs) {
  if (!(pkg %in% installed.packages())) {
    install.packages(pkg)
  }
}

# detach packages
default <- c(".GlobalEnv", "tools:rstudio", "tools:vscode",
             "package:stats", "package:graphics",
             "package:grDevices", "package:utils",
             "package:datasets", "package:methods",
             "Autoloads", "package:base")
for (pkg in setdiff(search(), default)) {
  detach(pkg, character.only = TRUE)
  }

# clear objects
remove(list=objects())
```

## パッケージの概要

gghighlight パッケージは、ggplot2 パッケージで作成されたプロットの特定の部分だけを強調する機能に特化したパッケージです。使い方はとても簡単で、ggplot オブジェクトの最終レイヤーとして gghighlight() 関数を追加し、強調したいデータの条件を指定するだけです。

## プロットの一部を強調する

```{r import, message = FALSE}
library(gghighlight)
```

```{r gghighlight::gghighlight, geom_line, message = FALSE}
# 折れ線グラフの一部を強調する
ggplot(ChickWeight, aes(x = Time, y = weight, group = Chick)) +
  geom_line(color='gray20') +
  gghighlight(max(weight) > 330)
```

```{r gghitglight::gghighlight, geom_point}
# 散布図の一部を強調する
library(tibble) # rownames_to_column() 関数を利用
ggplot(rownames_to_column(USArrests, 'State'), # 行の名前を列に変換
       aes(x = Murder, y = Assault)) +
  geom_point(col='darkcyan') + 
  gghighlight(grepl('New', State), label_key = State)
```

```{r gghitglight::gghighlight, geom_bar, message = FALSE}
# 棒グラフ、ヒストグラムの一部を強調する
ggplot(iris, aes(x = Sepal.Width, fill = Species)) +
  geom_histogram(bins = 10) +
  gghighlight() +
  facet_wrap(~Species)
```

## 参考資料

gghighlight パッケージの便利な使い方について、作者である湯谷啓明氏が解説スライドを公開しています。\
https://yutani.quarto.pub/tokyor-109-gghighlight/#/title-slide
