---
title: "gghighlight"
author: "データサイエンス関連基礎調査WG"
date: "`r Sys.Date()`"
format:
  html:
    fig-width: 6
    fig-height: 3
---

```{r setup, include=FALSE}

# install packages
pkgs <- c("ggplot2", "gghighlight", "tibble")
for (pkg in pkgs) {
  if (!(pkg %in% installed.packages())) {
    install.packages(pkg)
  }
}

# detach packages
default <- c(".GlobalEnv", "tools:rstudio", "tools:vscode",
             "package:stats", "package:graphics",
             "package:grDevices", "package:utils",
             "package:datasets", "package:methods",
             "Autoloads", "package:base")
for (pkg in setdiff(search(), default)) {
  detach(pkg, character.only = TRUE)
  }

# clear objects
remove(list=objects())
```

## パッケージの概要

[**gghighlight**](https://CRAN.R-project.org/package=gghighlight) パッケージは、**ggplot2** で作成したプロットの中から、特定の部分だけを強調表示するための機能に特化したツールです。使い方は非常にシンプルで、"ggplot" オブジェクトの最後のレイヤーとして `gghighlight()` 関数を追加し、強調したいデータの条件を指定するだけ利用できます。

## プロットの一部を強調する

```{r import, message = FALSE}
library(gghighlight)
```

### 折れ線グラフの一部を強調する

```{r gghighlight::gghighlight, geom_line, message = FALSE}
ggplot(ChickWeight, aes(x = Time, y = weight, group = Chick)) +
  geom_line(color='gray20') +
  gghighlight(max(weight) > 330)
```

### 散布図の一部を強調する

```{r gghitglight::gghighlight, geom_point}
library(tibble) # rownames_to_column() 関数を利用
ggplot(rownames_to_column(USArrests, 'State'), # 行の名前を列に変換
       aes(x = Murder, y = Assault)) +
  geom_point(col='darkcyan') + 
  gghighlight(grepl('New', State), label_key = State)
```

### 棒グラフ、ヒストグラムの一部を強調する

```{r gghitglight::gghighlight, geom_bar, message = FALSE}
ggplot(iris, aes(x = Sepal.Width, fill = Species)) +
  geom_histogram(bins = 10) +
  gghighlight() +
  facet_wrap(~Species)
```

## 参考資料

\[1\] 湯谷啓明. "gghighlight の作者です。すべてをお話しします。". パッケージの作者による解説スライド. https://yutani.quarto.pub/tokyor-109-gghighlight/
