---
  title: "psych"
  author: "DSWG"
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  echo=T,     # chunk表示の有無
  warning=F, # 警告表示の有無
  message=F,  # メッセージ表示の有無
)

# install packages
pkgs <- c("psych")
install.packages(pkgs[!pkgs %in% list.files(.libPaths())])
```

## packageのインストール

psychパッケージをインストールする。

```{r}
# install.packages("psych")
library(psych)
```

## pairs.panels関数（散布図・相関・ヒストグラム）

psych関数の代表的な関数pairs.panels()を使用すると、散布図・相関行・ヒストグラムを表示することができる。以下では、Rに標準で用意されているirisのデータセットを用いる。psychパッケージのdescribe関数でデータの統計量などを確認できる

```{r}
head(iris)
summary(iris)
describe(iris)
pairs.panels(iris)
```

Speciesの値によって、散布図を色分けすることも可能

```{r}
pairs.panels(iris[1:4],bg=c("red","yellow","blue")[iris$Species],
        pch=21,main="Fisher Iris data by Species")
pairs.panels(iris[1:4],bg=c("red","yellow","blue")[iris$Species],
  pch=21+as.numeric(iris$Species),main="Fisher Iris data by Species",hist.col="red") 
```

show.pointsの引数をFalseとすると散布図を表示しない。

```{r}
pairs.panels(iris,show.points=FALSE)
```
