name: Render and Publish

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.0' # R version

      - name: Install System Dependencies for R Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libfontconfig1-dev \
            libcairo2-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render book
        run: quarto render
      
      - name: Commit and Push _freeze updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update _freeze directory [skip ci]"
          file_pattern: "_freeze/**"
          commit_user_name: "GitHub Actions [Bot]"
          commit_user_email: "actions@github.com"
 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          user_name: "GitHub Actions [Bot]"
          user_email: "actions@github.com"
