name: Render and Publish

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v3
        with:
          r-version: 'renv'

      - name: Install System Dependencies for R Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libfontconfig1-dev \
            libcairo2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libcurl4-openssl-dev \
            libjpeg-dev \
            libpng-dev \
            unixodbc-dev

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push _freeze updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update _freeze cache [skip ci]"
          file_pattern: "_freeze/"
